---
# handlers file for ansible-role-samba-ad-member
- name: "restart_samba_services"
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items:
    - smbd
    - nmbd
    - winbind